name: push-master

on:
  push:
    branches: [master]

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  push-master:
    name: Push master
    runs-on: ubuntu-latest
    steps:

      - name: Generate coverage report 📦
        run: npm run test:coverage:push