name: push-master

on:
  push:
    branches: [master]

jobs:
  call-workflow:
    uses: web-hand/web-hand/.github/workflows/lint-and-test.yml@main

  push-master:
    name: Push master
    runs-on: ubuntu-latest
    steps:

      - name: Generate coverage report 📦
        run: npm run test:coverage:push